### PR TITLE
Feat:RDCC-5867:eLinks : Create a new schema & tables for Judicial Reference Data

### PR DESCRIPTION
**Pull request by shivajihmcts**
### JIRA link###

https://tools.hmcts.net/jira/browse/RDCC-5867

### Change description ###

eLinks : Create a new schema & tables for Judicial Reference Data

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[ x] No
```

### CODE REVIEW

**Review by AdilOoze — APPROVED** [review]

**Review by nayeemshaik-hmcts — COMMENTED** [review]
Can you verify the judicial_role_type , it should contains role_id serial NOT NULL,

**Review by nayeemshaik-hmcts — COMMENTED** [review]
Can we add additional constraints during the table creation it self?

**Comment by shivajihmcts** [comment]
> Can we add additional constraints during the table creation it self?

Its not required as discussed

**Review by nayeemshaik-hmcts — COMMENTED** [review]
Can we add schemas to flyway properties?

**Review by nayeemshaik-hmcts — APPROVED** [review]

**Review by vilasshelke-hmcts — APPROVED** [review]

**Review by nayeemshaik-hmcts — APPROVED** [review]

**Review by vilasshelke-hmcts — APPROVED** [review]

**Review by sahitya-desireddy — APPROVED** [review]

**Comment by shivajihmcts** [comment]
Merged changes in https://tools.hmcts.net/jira/browse/RDCC-5868

**Pull request closed without merging**
